export const siteConfig = {
  name: 'MarketingCo',
  nameAr: 'ماركتنج كو',
  description: 'Professional Digital Marketing Agency - We help businesses grow through strategic digital marketing solutions.',
  descriptionAr: 'وكالة تسويق رقمي احترافية - نساعد الشركات على النمو من خلال حلول التسويق الرقمي الاستراتيجية.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'https://marketingco.com',
  ogImage: '/images/og-image.png',
  links: {
    twitter: 'https://twitter.com/marketingco',
    linkedin: 'https://linkedin.com/company/marketingco',
    facebook: 'https://facebook.com/marketingco',
    instagram: 'https://instagram.com/marketingco',
    github: 'https://github.com/marketingco',
  },
  contact: {
    email: 'hello@marketingco.com',
    phone: '+1 (555) 123-4567',
    address: '123 Marketing Street, Business City, BC 12345',
  },
}

export type SiteConfig = typeof siteConfig

export const navConfig = {
  mainNav: [
    {
      title: 'Services',
      titleAr: 'الخدمات',
      href: '/services',
    },
    {
      title: 'About',
      titleAr: 'من نحن',
      href: '/about',
    },
    {
      title: 'Case Studies',
      titleAr: 'دراسات الحالة',
      href: '/case-studies',
    },
    {
      title: 'Blog',
      titleAr: 'المدونة',
      href: '/blog',
    },
    {
      title: 'Contact',
      titleAr: 'اتصل بنا',
      href: '/contact',
    },
  ],
  dashboardNav: [
    {
      title: 'Dashboard',
      titleAr: 'لوحة التحكم',
      href: '/dashboard',
      icon: 'LayoutDashboard',
    },
    {
      title: 'Projects',
      titleAr: 'المشاريع',
      href: '/dashboard/projects',
      icon: 'FolderKanban',
    },
    {
      title: 'Campaigns',
      titleAr: 'الحملات',
      href: '/dashboard/campaigns',
      icon: 'Megaphone',
    },
    {
      title: 'Content',
      titleAr: 'المحتوى',
      href: '/dashboard/content',
      icon: 'FileText',
    },
    {
      title: 'Analytics',
      titleAr: 'التحليلات',
      href: '/dashboard/analytics',
      icon: 'BarChart3',
    },
    {
      title: 'Reports',
      titleAr: 'التقارير',
      href: '/dashboard/reports',
      icon: 'FileBarChart',
    },
    {
      title: 'Tasks',
      titleAr: 'المهام',
      href: '/dashboard/tasks',
      icon: 'CheckSquare',
    },
    {
      title: 'Messages',
      titleAr: 'الرسائل',
      href: '/dashboard/messages',
      icon: 'MessageSquare',
    },
    {
      title: 'Clients',
      titleAr: 'العملاء',
      href: '/dashboard/clients',
      icon: 'Users',
      roles: ['SUPER_ADMIN', 'ADMIN', 'AGENCY_MANAGER', 'ACCOUNT_MANAGER'],
    },
    {
      title: 'Team',
      titleAr: 'الفريق',
      href: '/dashboard/team',
      icon: 'UserCog',
      roles: ['SUPER_ADMIN', 'ADMIN', 'AGENCY_MANAGER'],
    },
    {
      title: 'Invoices',
      titleAr: 'الفواتير',
      href: '/dashboard/invoices',
      icon: 'Receipt',
    },
    {
      title: 'Proposals',
      titleAr: 'العروض',
      href: '/dashboard/proposals',
      icon: 'FileSignature',
      roles: ['SUPER_ADMIN', 'ADMIN', 'AGENCY_MANAGER', 'ACCOUNT_MANAGER'],
    },
    {
      title: 'Settings',
      titleAr: 'الإعدادات',
      href: '/dashboard/settings',
      icon: 'Settings',
    },
  ],
}

export const servicesConfig = [
  {
    id: 'seo',
    title: 'Search Engine Optimization',
    titleAr: 'تحسين محركات البحث',
    slug: 'seo',
    description: 'Improve your website visibility and organic search rankings.',
    descriptionAr: 'تحسين ظهور موقعك وترتيبه في نتائج البحث العضوية.',
    icon: 'Search',
    features: [
      'Technical SEO Audit',
      'Keyword Research & Strategy',
      'On-Page Optimization',
      'Link Building',
      'Local SEO',
      'SEO Reporting',
    ],
    featuresAr: [
      'تدقيق SEO التقني',
      'بحث الكلمات المفتاحية والاستراتيجية',
      'تحسين الصفحات',
      'بناء الروابط',
      'SEO المحلي',
      'تقارير SEO',
    ],
  },
  {
    id: 'ppc',
    title: 'Pay-Per-Click Advertising',
    titleAr: 'إعلانات الدفع مقابل النقرة',
    slug: 'ppc',
    description: 'Drive targeted traffic with strategic paid advertising campaigns.',
    descriptionAr: 'جذب حركة مرور مستهدفة من خلال حملات إعلانية مدفوعة استراتيجية.',
    icon: 'MousePointerClick',
    features: [
      'Google Ads Management',
      'Display Advertising',
      'Shopping Ads',
      'Remarketing Campaigns',
      'Landing Page Optimization',
      'Conversion Tracking',
    ],
    featuresAr: [
      'إدارة إعلانات جوجل',
      'الإعلانات المرئية',
      'إعلانات التسوق',
      'حملات إعادة الاستهداف',
      'تحسين الصفحات المقصودة',
      'تتبع التحويلات',
    ],
  },
  {
    id: 'social-media',
    title: 'Social Media Marketing',
    titleAr: 'التسويق عبر وسائل التواصل',
    slug: 'social-media',
    description: 'Build brand awareness and engage your audience on social platforms.',
    descriptionAr: 'بناء الوعي بالعلامة التجارية والتفاعل مع جمهورك على منصات التواصل.',
    icon: 'Share2',
    features: [
      'Social Media Strategy',
      'Content Creation & Scheduling',
      'Community Management',
      'Social Advertising',
      'Influencer Marketing',
      'Analytics & Reporting',
    ],
    featuresAr: [
      'استراتيجية وسائل التواصل',
      'إنشاء المحتوى والجدولة',
      'إدارة المجتمع',
      'الإعلانات الاجتماعية',
      'التسويق عبر المؤثرين',
      'التحليلات والتقارير',
    ],
  },
  {
    id: 'content-marketing',
    title: 'Content Marketing',
    titleAr: 'التسويق بالمحتوى',
    slug: 'content-marketing',
    description: 'Create valuable content that attracts and converts your audience.',
    descriptionAr: 'إنشاء محتوى قيم يجذب جمهورك ويحوله إلى عملاء.',
    icon: 'FileEdit',
    features: [
      'Content Strategy',
      'Blog Writing',
      'Video Production',
      'Infographic Design',
      'eBook & Whitepaper Creation',
      'Content Distribution',
    ],
    featuresAr: [
      'استراتيجية المحتوى',
      'كتابة المدونات',
      'إنتاج الفيديو',
      'تصميم الإنفوجرافيك',
      'إنشاء الكتب الإلكترونية',
      'توزيع المحتوى',
    ],
  },
  {
    id: 'email-marketing',
    title: 'Email Marketing',
    titleAr: 'التسويق عبر البريد الإلكتروني',
    slug: 'email-marketing',
    description: 'Nurture leads and drive conversions with targeted email campaigns.',
    descriptionAr: 'رعاية العملاء المحتملين وتحقيق التحويلات من خلال حملات البريد المستهدفة.',
    icon: 'Mail',
    features: [
      'Email Strategy & Planning',
      'Template Design',
      'List Segmentation',
      'Automation Workflows',
      'A/B Testing',
      'Performance Analytics',
    ],
    featuresAr: [
      'استراتيجية وتخطيط البريد',
      'تصميم القوالب',
      'تقسيم القوائم',
      'سير عمل الأتمتة',
      'اختبار A/B',
      'تحليلات الأداء',
    ],
  },
  {
    id: 'branding',
    title: 'Brand Development',
    titleAr: 'تطوير العلامة التجارية',
    slug: 'branding',
    description: 'Build a strong brand identity that resonates with your audience.',
    descriptionAr: 'بناء هوية علامة تجارية قوية تتفاعل مع جمهورك.',
    icon: 'Palette',
    features: [
      'Brand Strategy',
      'Logo & Identity Design',
      'Brand Guidelines',
      'Visual Identity',
      'Brand Messaging',
      'Brand Positioning',
    ],
    featuresAr: [
      'استراتيجية العلامة التجارية',
      'تصميم الشعار والهوية',
      'إرشادات العلامة التجارية',
      'الهوية البصرية',
      'رسائل العلامة التجارية',
      'تموضع العلامة التجارية',
    ],
  },
]

export const pricingPlans = [
  {
    id: 'starter',
    name: 'Starter',
    nameAr: 'المبتدئ',
    description: 'Perfect for small businesses getting started with digital marketing',
    descriptionAr: 'مثالي للشركات الصغيرة التي تبدأ في التسويق الرقمي',
    price: 999,
    currency: 'USD',
    billingCycle: 'monthly',
    features: [
      'Up to 3 active campaigns',
      '1 dedicated account manager',
      'Monthly reporting',
      'Email support',
      'Basic analytics dashboard',
      'Social media management (2 platforms)',
    ],
    featuresAr: [
      'حتى 3 حملات نشطة',
      'مدير حساب مخصص',
      'تقارير شهرية',
      'دعم عبر البريد',
      'لوحة تحليلات أساسية',
      'إدارة وسائل التواصل (منصتان)',
    ],
    popular: false,
  },
  {
    id: 'growth',
    name: 'Growth',
    nameAr: 'النمو',
    description: 'Ideal for growing businesses looking to scale their marketing efforts',
    descriptionAr: 'مثالي للشركات النامية التي تتطلع إلى توسيع جهودها التسويقية',
    price: 2499,
    currency: 'USD',
    billingCycle: 'monthly',
    features: [
      'Up to 10 active campaigns',
      '2 dedicated team members',
      'Weekly reporting',
      'Priority support',
      'Advanced analytics & insights',
      'Social media management (5 platforms)',
      'Content creation (12 pieces/month)',
      'SEO optimization',
    ],
    featuresAr: [
      'حتى 10 حملات نشطة',
      'عضوان مخصصان من الفريق',
      'تقارير أسبوعية',
      'دعم ذو أولوية',
      'تحليلات ورؤى متقدمة',
      'إدارة وسائل التواصل (5 منصات)',
      'إنشاء المحتوى (12 قطعة/شهر)',
      'تحسين SEO',
    ],
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    nameAr: 'المؤسسي',
    description: 'Comprehensive solution for large organizations with complex needs',
    descriptionAr: 'حل شامل للمؤسسات الكبيرة ذات الاحتياجات المعقدة',
    price: null, // Custom pricing
    currency: 'USD',
    billingCycle: 'custom',
    features: [
      'Unlimited campaigns',
      'Dedicated agency team',
      'Daily reporting & insights',
      '24/7 support',
      'Custom analytics & BI dashboards',
      'Full social media management',
      'Unlimited content creation',
      'Advanced SEO & technical optimization',
      'Marketing automation',
      'Custom integrations',
    ],
    featuresAr: [
      'حملات غير محدودة',
      'فريق وكالة مخصص',
      'تقارير ورؤى يومية',
      'دعم 24/7',
      'لوحات تحليلات ذكاء أعمال مخصصة',
      'إدارة كاملة لوسائل التواصل',
      'إنشاء محتوى غير محدود',
      'SEO متقدم وتحسين تقني',
      'أتمتة التسويق',
      'تكاملات مخصصة',
    ],
    popular: false,
  },
]
